# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhotoBrowserDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PhotoBrowserDemo
    #Default core
    pod 'ZYQPhotoBrowser', :path => '../ZYQPhotoBrowser.podspec'


  target 'PhotoBrowserDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhotoBrowserDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PhotoBrowserCustomCoreDemo' do

#NoDependency custom core
pod 'ZYQPhotoBrowser-NoDependency', :path => '../ZYQPhotoBrowser-NoDependency.podspec'
pod 'YYWebImage'
pod 'YYImage/WebP'
pod 'DACircularProgress'
end
